name: Gfxstream Presubmit

on:
  pull_request:
  push:
    branches-ignore:
      - main  # push events to main branch occur after PRs are merged, when the same checks were run

concurrency:
  # limits the workflow to a single run per branch/PR
  group: ${{ github.workflow }}-${{ github.ref }}
  # previous runs are cancelled when a new run is started
  cancel-in-progress: true

jobs:
  run-gfxstream-bazel-end2end-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh
    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh
    - name: Install runtime dependencies
      run: sudo apt-get install -y libvulkan1
    - name: Load cache config
      run: cat .config/cache-config.env >> $GITHUB_ENV
    - name: Mount Bazel cache
      uses: actions/cache/restore@v4
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-bazel-disk-cache-{2}-{3}-{4}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name, github.sha) }}
        restore-keys: |
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-{3}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name) || '' }}
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-main-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures
    - name: Run unit tests
      run: |
        bazel test \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --test_output=streamed \
          --verbose_failures \
          host/vulkan:gfxstream_emulatedphysicalmemory_tests \
          tests/end2end:gfxstream_end2end_tests
  run-gfxstream-bazel-end2end-tests-arm:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh
    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh
    - name: Install runtime dependencies
      run: sudo apt-get install -y libvulkan1
    - name: Load cache config
      run: cat .config/cache-config.env >> $GITHUB_ENV
    - name: Mount Bazel cache
      uses: actions/cache/restore@v4
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-bazel-disk-cache-{2}-{3}-{4}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name, github.sha) }}
        restore-keys: |
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-{3}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name) || '' }}
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-main-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
          ${{ format('{0}-{1}-bazel-disk-cache-{2}-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures
  run-gfxstream-cmake-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install toolchain dependencies
      run: sudo bash toolchain/cmake/install_toolchain_dependencies.sh
    - name: Configure Build
      run: |
        mkdir build && \
        cd build && \
        cmake .. -G Ninja
    - name: Build
      run: |
        cd build && \
        ninja
  run-gfxstream-meson-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install toolchain dependencies
      run: sudo bash toolchain/meson/install_toolchain_dependencies.sh
    - name: Configure Build
      run: |
        meson setup \
          -Ddefault_library=static \
          -Dgfxstream-build=host \
          build
    - name: Build
      run: |
        meson compile -C build
  run-gfxstream-meson-build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout current PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            git
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-headers-git
      - name: Configure Build
        run: meson setup build
      - name: Build
        run: meson compile -C build
